# mbu my first python program
print("Hello, World!")  
print("Welcome to Python programming.")
print ("This is my first program in Python.")
print("I am excited to learn Python!")
print("Python is a great language for beginners.")
print("I will practice coding every day.")
print("I am looking forward to creating amazing projects with Python.") 
print("Let's get started with Python programming!")
print("Thank you for reading my first Python program.")
print("Goodbye, World!")
print("This is the end of my first Python program.")
print("I hope you enjoyed reading my first Python program.")
print("I am proud of myself for writing my first Python program.")
print("I can't wait to learn more about Python programming.")
print("Python is a powerful and versatile programming language.")
print("I am excited to see what I can create with Python.")
print("I will keep practicing and improving my Python skills.") 
print("Python programming is fun and rewarding.")
print("I am grateful for the opportunity to learn Python programming.")
print("I am excited to see what the future holds for me as a Python programmer.")
